### PR TITLE
Add environment variable 'COMPANIES_HOUSE_API_KEY

### PR DESCRIPTION
**Pull request by GhazanfarMir**
Add environment variable 'COMPANIES_HOUSE_API_KEY

### CODE REVIEW

**Comment by GhazanfarMir** [comment]
Specify how this should be set in tests.

**Comment by matthewnw** [comment]
@GhazanfarMir Would you also be able to add in the env variable for the base_uri in the config file? Not likely to change but seeing as it is in the config file. Thanks!

**Comment by GhazanfarMir** [comment]
> @GhazanfarMir Would you also be able to add in the env variable for the base_uri in the config file? Not likely to change but seeing as it is in the config file. Thanks!

Just thought about it and don't think URI should go into the environment variables. URI remains same irrespective of which environment you are on. Only thing that should change is the API key as you may have different keys per environment.

However, I agree, it shouldn't be hard coded in `CompaniesHouseServiceProvider.php` and loaded from `config/companies.php` instead. I am going to fix this as soon as I get some free time on my hands.

**Comment by matthewnw** [comment]
> > @GhazanfarMir Would you also be able to add in the env variable for the base_uri in the config file? Not likely to change but seeing as it is in the config file. Thanks!
> 
> Just thought about it and don't think URI should go into the environment variables. URI remains same irrespective of which environment you are on. Only thing that should change is the API key as you may have different keys per environment.
> 
> However, I agree, it shouldn't be hard coded in `CompaniesHouseServiceProvider.php` and loaded from `config/companies.php` instead. I am going to fix this as soon as I get some free time on my hands.

Ah yes my mistake, I meant from the config() setting not env(). Thanks

**Pull request merged**
