### PR TITLE
Added backwards compatibility for Laravel 5.8, 6 & 7.

### LINKED ISSUE #24: Add Laravel 6 and 7 support
Would it be possible to Laravel 6 support please?

### PR DESCRIPTION
**Pull request by matthewnw**
Closes #24
Downgraded requirement to PHP 7.2 minimum.

### CODE REVIEW

**Comment by matthewnw** [comment]
@GhazanfarMir Hey, have you had chance to look at this pull? Thanks!

**Comment by matthewnw** [comment]
@GhazanfarMir Legend, thanks!

**Comment by matthewnw** [comment]
@GhazanfarMir Would you be able to manually update packagist? Doesn't seem to want to auto update by the looks. Thanks!

**Comment by GhazanfarMir** [comment]
I did update manually earlier, not sure why packagist isnt updating stable
version.

**Comment by GhazanfarMir** [comment]
Ok this is now sorted.

Please update package.

**Pull request merged**
